[package]
name = "whiz"
version = "0.1.0"
edition = "2021"
description = "Modern DAG/tasks runner for multi-platform monorepos."
license = "MPL-2.0"

[dependencies]
actix = "0.13.0"
ansi-to-tui = "2.0.0"
anyhow = "1.0.68"
chrono = "0.4.23"
clap = { version = "4.1.1", features = ["derive"] }
crossterm = "0.25.0"
dotenv-parser = "0.1.3"
globset = "0.4.10"
ignore = "0.4.20"
indexmap = { version = "1.9.2", features = ["serde"] }
notify = "5.0.0"
path-absolutize = "3.0.14"
path-clean = "0.1.0"
regex = "1.7.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_yaml = "0.9.17"
strip-ansi-escapes = "0.1.1"
subprocess = "0.2.9"
textwrap = "0.16.0"
tui = "0.19.0"
url = "2.3.1"
