[package]
name = "whiz"
version = "0.5.1-beta.1"
edition = "2021"
description = "Modern DAG/tasks runner for multi-platform monorepos."
license = "MPL-2.0"

[dependencies]
actix = "0.13.1"
ansi-to-tui = "3.1.0"
anyhow = "1.0.75"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.6", features = ["derive"] }
crossterm = "0.27.0"
directories = "5.0.1"
dotenv-parser = "0.1.3"
globset = "0.4.13"
ignore = "0.4.20"
indexmap = { version = "2.0.2", features = ["serde"] }
# lade-sdk = { path = "../../github/lade/sdk"}
lade-sdk = "0.8.1"
openssl = { version = "0.10.57", features = ["vendored"] }
notify = "6.1.1"
path-absolutize = "3.1.1"
path-clean = "1.0.1"
regex = "1.9.6"
self_update = { version = "0.38.0", features = [
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
  "compression-zip-bzip2",
] }
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.25"
strip-ansi-escapes = "0.2.0"
subprocess = "0.2.9"
textwrap = "0.16.0"
tokio = { version = "1.32.0", features = ["full"] }
ratatui = "0.23.0"
url = "2.4.1"
assert_cmd = "2.0.12"
semver = "1.0.19"
shlex = "1.2.0"
