[package]
name = "whiz"
version = "0.3.3-beta.1"
edition = "2021"
description = "Modern DAG/tasks runner for multi-platform monorepos."
license = "MPL-2.0"

[dependencies]
actix = "0.13.0"
ansi-to-tui = "3.0.0"
anyhow = "1.0.70"
chrono = "0.4.24"
clap = { version = "4.2.1", features = ["derive"] }
crossterm = "0.26.1"
dotenv-parser = "0.1.3"
globset = "0.4.10"
ignore = "0.4.20"
indexmap = { version = "1.9.3", features = ["serde"] }
lade-sdk = "0.5.0"
notify = "5.1.0"
openssl = { version = "0.10.49", features = ["vendored"] }
path-absolutize = "3.0.14"
path-clean = "1.0.1"
regex = "1.7.3"
self_update = { version = "0.36.0", features = [
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
  "compression-zip-bzip2",
] }
serde = { version = "1.0.159", features = ["derive"] }
serde_yaml = "0.9.19"
strip-ansi-escapes = "0.1.1"
subprocess = "0.2.9"
textwrap = "0.16.0"
tui = {version = "0.20.1", package = "ratatui"}
url = "2.3.1"
