[package]
name = "whiz"
version = "0.4.3-beta.1"
edition = "2021"
description = "Modern DAG/tasks runner for multi-platform monorepos."
license = "MPL-2.0"

[dependencies]
actix = "0.13.0"
ansi-to-tui = "3.1.0"
anyhow = "1.0.71"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.2", features = ["derive"] }
crossterm = "0.26.1"
directories = "5.0.1"
dotenv-parser = "0.1.3"
globset = "0.4.10"
ignore = "0.4.20"
indexmap = { version = "1.9.3", features = ["serde"] }
# lade-sdk = { path = "../../github/lade/sdk"}
lade-sdk = "0.6.2"
openssl = { version = "0.10.54", features = ["vendored"] }
notify = "6.0.1"
path-absolutize = "3.1.0"
path-clean = "1.0.1"
regex = "1.8.4"
self_update = { version = "0.37.0", features = [
  "archive-tar",
  "archive-zip",
  "compression-flate2",
  "compression-zip-deflate",
  "compression-zip-bzip2",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
strip-ansi-escapes = "0.1.1"
subprocess = "0.2.9"
textwrap = "0.16.0"
tokio = { version = "1.29.1", features = ["full"] }
tui = {version = "0.21.0", package = "ratatui"}
url = "2.4.0"
assert_cmd = "2.0.11"
